version: "3.9"

services:
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE
    volumes:
      - ./shared/etc:/etc/suricata
      - ./shared/logs:/var/log/suricata
      - ./shared/data:/var/lib/suricata
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    command: ["-i", "eth1"]
    restart: unless-stopped
